name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'NietDiscord/ui'
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name : Cache
      uses: actions/cache@v2
      with:
        path: "frontend/node_modules"
        key: node-modules-${{ hashFiles('NietDiscord/ui/package.json') }}
    - run: npm ci
      working-directory: ./NietDiscord/ui
    - run: npm run build --if-present
      working-directory: ./NietDiscord/ui



#   docker:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: 'NietDiscord/ui'
#     steps:
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       -
#         name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_TOKEN }}
#       -
#         name: Build and push
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           file: ./NietDiscord/ui/Dockerfile
#           push: true
#           tags: jensdoomen/nietdiscordui:latest
          
          
#   sonarcloud:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         # Disabling shallow clone is recommended for improving relevancy of reporting
#         fetch-depth: 0
#     - name: SonarCloud Scan
#       uses: sonarsource/sonarcloud-github-action@master
#       with:
#         projectBaseDir: NietDiscord
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}



# name: Node.js CI

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:

#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: 'NietDiscord/ui'
#     strategy:
#       matrix:
#         node-version: [14.x]
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v2
#       with:
#         node-version: ${{ matrix.node-version }}
#     - name : Cache
#       uses: actions/cache@v2
#       with:
#         path: "frontend/node_modules"
#         key: node-modules-${{ hashFiles('NietDiscord/ui/package.json') }}
#     - run: npm ci
#       working-directory: ./NietDiscord/ui
#     - run: npm run build --if-present
#       working-directory: ./NietDiscord/ui
