name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'NietDiscord/ui'
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name : Cache
      uses: actions/cache@v2
      with:
        path: "frontend/node_modules"
        key: node-modules-${{ hashFiles('NietDiscord/ui/package.json') }}
    - run: npm ci
      working-directory: ./NietDiscord/ui
    - run: npm run build --if-present
      working-directory: ./NietDiscord/ui
